spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/federation_agricole_db

spring.datasource.username=federation_admin
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

# Désactive l'auto-configuration JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging.level.org.springframework.jdbc.core=DEBUG